### ISSUE TITLE
Product Name

### ISSUE THREAD

**Issue by NickChapman** [juan-t0rres/mock-interview-app#28]
We need to figure out what this site is actually called.

**Comment by alexschles** [comment]
I’m just going to throw out some name ideas that I’m forcing myself to think of. Sorry if they’re horrible.

MatchMocker
CodePair
PrepTech
CodeBuddy
CodeConnect
InterviewU (both because it’s to find someone to interview you or for you to interview, and also because it’s mostly for University students)

**Comment by juan-t0rres** [comment]
Even though it's a little cheesy I think MatchMocker is perfect lol

**Comment by NickChapman** [comment]
Looks like we have settled on MatchMocker, so I'm going to mark this as resolved.
